gpu_list:
    - 0
seed: null
dump_path: '/opt/ppd/hyperk/Users/samanis/WatChMaL/outputs/resnet18/firstred_net/anglered_test/'
defaults:
    - data: sk_full
    - data/dataset: sk_full_cnn
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet_fc
    - engine: classifier
    - tasks/restore_state: restore_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
