gpu_list:
    - 0
    - 1
seed: null
dump_path: '/opt/ppd/hyperk/Users/samanis/WatChMaL/outputs/resnet18/firstred_valbatch/'
defaults:
    - data: sk_full
    - data/dataset: sk_full_cnn
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet_fc
    - engine: classifier
    - tasks/train: train_resnet
    - optimizers@tasks.train.optimizers: adam
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
